files:
  - { package: system_diagnostic_monitor, path: config/map.yaml }
  - { package: system_diagnostic_monitor, path: config/localization.yaml }
  - { package: system_diagnostic_monitor, path: config/planning.yaml }
  - { package: system_diagnostic_monitor, path: config/perception.yaml }
  - { package: system_diagnostic_monitor, path: config/control.yaml }
  - { package: system_diagnostic_monitor, path: config/vehicle.yaml }
  - { package: system_diagnostic_monitor, path: config/system.yaml }

nodes:
  - path: /autoware/modes/stop
    type: debug-ok

  - path: /autoware/modes/autonomous
    type: and
    list:
      - { type: link, path: /autoware/map }
      - { type: link, path: /autoware/localization }
      - { type: link, path: /autoware/planning }
      - { type: link, path: /autoware/perception }
      - { type: link, path: /autoware/control }
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/modes/local
    type: and
    list:
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/modes/remote
    type: and
    list:
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/modes/emergency-stop
    type: and
    list:
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/modes/comfortable-stop
    type: and
    list:
      - { type: link, path: /autoware/map }
      - { type: link, path: /autoware/localization }
      - { type: link, path: /autoware/planning }
      - { type: link, path: /autoware/perception }
      - { type: link, path: /autoware/control }
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/modes/pull-over
    type: and
    list:
      - { type: link, path: /autoware/map }
      - { type: link, path: /autoware/localization }
      - { type: link, path: /autoware/planning }
      - { type: link, path: /autoware/perception }
      - { type: link, path: /autoware/control }
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }
