units:
  - path: /autoware/control
    type: and
    list:
      - { type: link, path: /autoware/control/topic_rate_check/trajectory_follower }
      - { type: link, path: /autoware/control/topic_rate_check/control_command }

diags:
  - path: /autoware/control/topic_rate_check/trajectory_follower
    name: "topic_state_monitor_trajectory_follower_control_cmd: control_topic_status"
    hardware: topic_state_monitor

  - path: /autoware/control/topic_rate_check/control_command
    name: "topic_state_monitor_control_command_control_cmd: control_topic_status"
    hardware: topic_state_monitor
