nodes:
  - path: /autoware/localization
    type: and
    list:
      - { type: link, link: /autoware/localization/state }

  - path: /autoware/localization/state
    diag: "component_state_diagnostics: localization_state"
