units:
  - path: /autoware/map
    type: and
    list:
      - type: link
        path: /autoware/map/topic_rate_check/vector_map
      - type: link
        path: /autoware/map/topic_rate_check/pointcloud_map
        mode: { except: [psim] }

diags:
  - path: /autoware/map/topic_rate_check/vector_map
    name: "topic_state_monitor_vector_map: map_topic_status"
    hardware: topic_state_monitor

  - path: /autoware/map/topic_rate_check/pointcloud_map
    mode: { except: [psim] }
    name: "topic_state_monitor_pointcloud_map: map_topic_status"
    hardware: topic_state_monitor
