nodes:
  - path: /autoware/map
    type: and
    list:
      - { type: link, link: /autoware/map/topic_rate_check/vector_map }
      - { type: link, link: /autoware/map/topic_rate_check/pointcloud_map }

  - path: /autoware/map/topic_rate_check/vector_map
    diag: "topic_state_monitor_vector_map: map_topic_status"

  - path: /autoware/map/topic_rate_check/pointcloud_map
    diag: "topic_state_monitor_pointcloud_map: map_topic_status"
