nodes:
  - path: /autoware/planning
    type: short-circuit-and
    list:
      - type: link
        link: /autoware/planning/routing/state
      - type: and
        list:
          - { type: link, link: /autoware/planning/topic_rate_check/route }
          - { type: link, link: /autoware/planning/topic_rate_check/trajectory }
          - { type: link, link: /autoware/planning/topic_rate_check/trajectory }
          - { type: link, link: /autoware/planning/trajectory-validation/finite }
          - { type: link, link: /autoware/planning/trajectory-validation/interval }
          - { type: link, link: /autoware/planning/trajectory-validation/curvature }
          - { type: link, link: /autoware/planning/trajectory-validation/angle }
          - { type: link, link: /autoware/planning/trajectory-validation/lateral-acceleration }
          - { type: link, link: /autoware/planning/trajectory-validation/acceleration }
          - { type: link, link: /autoware/planning/trajectory-validation/deceleration }
          - { type: link, link: /autoware/planning/trajectory-validation/steering }
          - { type: link, link: /autoware/planning/trajectory-validation/steering-rate }
          - { type: link, link: /autoware/planning/trajectory-validation/velocity-deviation }

  - path: /autoware/planning/routing/state
    diag: "component_state_diagnostics: route_state"

  - path: /autoware/planning/topic_rate_check/route
    diag: "topic_state_monitor_mission_planning_route: planning_topic_status"

  - path: /autoware/planning/topic_rate_check/trajectory
    diag: "topic_state_monitor_scenario_planning_trajectory: planning_topic_status"

  - path: /autoware/planning/trajectory-validation/finite
    diag: "planning_validator: trajectory_validation_finite"

  - path: /autoware/planning/trajectory-validation/interval
    diag: "planning_validator: trajectory_validation_interval"

  - path: /autoware/planning/trajectory-validation/curvature
    diag: "planning_validator: trajectory_validation_curvature"

  - path: /autoware/planning/trajectory-validation/angle
    diag: "planning_validator: trajectory_validation_relative_angle"

  - path: /autoware/planning/trajectory-validation/lateral-acceleration
    diag: "planning_validator: trajectory_validation_lateral_acceleration"

  - path: /autoware/planning/trajectory-validation/acceleration
    diag: "planning_validator: trajectory_validation_acceleration"

  - path: /autoware/planning/trajectory-validation/deceleration
    diag: "planning_validator: trajectory_validation_deceleration"

  - path: /autoware/planning/trajectory-validation/steering
    diag: "planning_validator: trajectory_validation_steering"

  - path: /autoware/planning/trajectory-validation/steering-rate
    diag: "planning_validator: trajectory_validation_steering_rate"

  - path: /autoware/planning/trajectory-validation/velocity-deviation
    diag: "planning_validator: trajectory_validation_velocity_deviation"
