nodes:
  - path: /autoware/vehicle
    type: and
    list:
      - { type: link, path: /autoware/vehicle/topic_rate_check/velocity }
      - { type: link, path: /autoware/vehicle/topic_rate_check/steering }

  - path: /autoware/vehicle/topic_rate_check/velocity
    name: "topic_state_monitor_vehicle_status_velocity_status: vehicle_topic_status"

  - path: /autoware/vehicle/topic_rate_check/steering
    name: "topic_state_monitor_vehicle_status_steering_status: vehicle_topic_status"
