nodes:
  - path: /localization
    type: short-circuit-and
    list:
      - type: link
        link: /localization/state
      - type: and
        list:
          - { type: link, link: /localization/state }
          - { type: link, link: /localization/topic_rate_check/transform }
          - { type: link, link: /localization/topic_rate_check/pose_twist_fusion }
          - { type: link, link: /localization/matching_score }
          - { type: link, link: /localization/accuracy }
          - { type: link, link: /localization/sensor_fusion_status }

  - path: /localization/state
    diag: "component_state_diagnostics: localization_state"

  - path: /localization/topic_rate_check/transform
    diag: "topic_state_monitor_transform_map_to_base_link: localization_topic_status"

  - path: /localization/topic_rate_check/pose_twist_fusion
    diag: "topic_state_monitor_pose_twist_fusion_filter_pose: localization_topic_status"

  - path: /localization/matching_score
    diag: ndt_scan_matcher

  - path: /localization/accuracy
    diag: "localization: localization_error_monitor"

  - path: /localization/sensor_fusion_status
    diag: "localization: ekf_localizer"
