nodes:
  - path: /perception
    type: and
    list:
      - { type: link, link: /perception/topic_rate_check/objects }
      - { type: link, link: /perception/topic_rate_check/pointcloud }

  - path: /perception/topic_rate_check/objects
    diag: "topic_state_monitor_object_recognition_objects: perception_topic_status"

  - path: /perception/topic_rate_check/pointcloud
    diag: "topic_state_monitor_obstacle_segmentation_pointcloud: perception_topic_status"
