files:
  - { path: $(find-pkg-share diagnostic_graph_monitor)/config.yaml }

edits:
  - { type: remove, path: /map/topic_rate_check/pointcloud_map }
  - { type: remove, path: /localization/matching_score }
  - { type: remove, path: /localization/accuracy }
  - { type: remove, path: /localization/sensor_fusion_status }
  - { type: remove, path: /localization/topic_rate_check/pose_twist_fusion }
  - { type: remove, path: /perception/topic_rate_check/pointcloud }
  - { type: remove, path: /control/emergency_braking }
