#!/usr/bin/env python3

import sys

import rqt_gui.main

rqt_main = rqt_gui.main.Main()
sys.exit(
    rqt_main.main(
        sys.argv, standalone="system_diagnostic_viewer.plugin.SystemDiagnosticMonitorPlugin"
    )
)
